# Generated by Django 5.1.7 on 2025-03-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='time_created',
        ),
        migrations.AddField(
            model_name='bill',
            name='ime_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
