# Generated by Django 5.1.7 on 2025-03-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_bill_time_created_bill_ime_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='ime_created',
        ),
        migrations.AddField(
            model_name='bill',
            name='time_created',
            field=models.DateTimeField(default='2024-03-20 00:00:00'),
            preserve_default=False,
        ),
    ]
